### ISSUE TITLE
Modification class Allele

### ISSUE THREAD

**Issue by marieanselmet** [EPFL-SV-cpp-projects/Team_13#10]
- If the nucleotide N, Y .. appears, we randomly chose A,T,G or C to replace it.
- enum Nucleotide and corresponding method to convert string -> nucleotide 

Points : 10

**Comment by ygrimault** [comment]
Everything looks fine, but I was wondering : do you work only on ADN, or will you also use ARN ? (In which case you should have an "U" nucleotide)
I'm closing the issue because the work is done, but you might need to think about it if you haven't already ^^
