### ISSUE TITLE
Construction of population from file

### ISSUE THREAD

**Issue by marieanselmet** [EPFL-SV-cpp-projects/Team_13#2]
Population created from a file (.fasta, .txt ...), read each line of the genomes to extract the nucleotide sequences corresponding to the markers. 
Initialize the number of alleles, size of the population, and all the alleles.
-> We build the population in the Simulation class

Points : 80

**Comment by emmaroussel** [comment]
The code corresponding to the "constructor of population" has been moved in the Simulation class (see extract_values method)
-> You will not find anything in the constructor of Population.
