### ISSUE TITLE
Création du groupe WhatsApp avec l'assistant

### ISSUE THREAD

**Issue by MarcBickel** [EPFL-SV-cpp-projects/Team_13#2]
Ecrivez votre numéro de téléphone en commentaire, et je créerai le groupe

**Comment by MarcBickel** [comment]
Mon numéro est +41 79 853 38 26

**Comment by tHeBiGbOsS1196** [comment]
Mon numéro est +41 79 594 05 49
Gregory Grandjean

**Comment by Leqr** [comment]
Mon numéro : 079 526 52 30
Léonard

**Comment by hgelblat** [comment]
mon numéro : +41787111789 (Hannah)

**Comment by BlancheBerneron** [comment]
Mon numéro est le +33627017782
Blanche

**Comment by AmauryMigeotte** [comment]
mon numéro : 078 626 88 55
