### ISSUE TITLE
Gtests

### ISSUE THREAD

**Issue by marieanselmet** [EPFL-SV-cpp-projects/Team_13#4]
Create first tests (test good behavior of the multinomial fonction, ...)

Points : 80

**Comment by ygrimault** [comment]
Before closing the issue, it might be nice to explain exactly which tests you created so we have a nice history.

**Comment by marieanselmet** [comment]
Tests for the inputs
Test for the multinomial distribution
Tests for the good behavior of the frequencies of the alleles during simulations
