### ISSUE TITLE
Class Simulation(skeleton+constructors)

### ISSUE THREAD

**Issue by marieanselmet** [EPFL-SV-cpp-projects/Team_13#8]
Create the simulation skeleton +  2 constructors  (one from file, one from explicit values, see comment below) 
Also add an update method which run the simulation for a known number of generations 

Points : 15

**Comment by emmaroussel** [comment]
Skeleton of class Simulation : 
- 2 ways to simulate : build the population via a file or via explicit values (see the 2 possible constructors of Simulation) 
Remark : the extract_values method is almost the same as the code of the (ancient) Population constructor (see previous Issue).
- update method : update each replica (-> update their frequencies) for a given number of generations
